### ISSUE TITLE
[#1]class import  불가

### ISSUE THREAD

**Issue by diasm3** [team-opensource-plus/dummy-generator#5]
1. 모듈을 만들고 export, import 하는 도중에 아래와 같은 메세지가 나오면서 import가 불가능한 문제가 생겼습니다.
2. tsconfig에서 module 부분을 commonjs , es6로 변경해보면서 했지만 안되었습니다.
3. require('') 방식으로 해봤지만 안되었습니다.

`internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../gptapi/api-caller'
Require stack:
- /Users/semyungpark/Documents/dev/dummy-generator/bin/dummy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/semyungpark/Documents/dev/dummy-generator/bin/dummy.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/semyungpark/Documents/dev/dummy-generator/bin/dummy.js' ]
}`

**Comment by diasm3** [comment]
해결완료 

절차는
1. ts 파일로 작성 
2. js 파일은 tsc로 생성 
3. js 파일 실행
4. 
루트 폴더 src로 잡아주고, 
src에 bin / dummy.ts 파일 만들고 작업해줬으면 될 것 같아요. 

package.json에서 
bin은 output 했을 때 dummy.js 파일 생성되는 위치만 잡아주면 됩니다.
